# Generated by Django 5.1.5 on 2026-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Datos extra como solicitud_id, paciente_id, etc.'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='sonido',
            field=models.BooleanField(default=False, help_text='True si la notificación debe reproducir un sonido'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('CITA', 'Nueva Cita'), ('ASIGNACION', 'Nueva Asignación'), ('SISTEMA', 'Aviso del Sistema'), ('SOLICITUD_GUARDADO', 'Solicitud de Guardado'), ('RESPUESTA_GUARDADO', 'Respuesta de Guardado'), ('SUPERVISION', 'Supervisión Requerida')], default='SISTEMA', max_length=30),
        ),
    ]
