# Generated by Django 6.0.3 on 2026-04-03 21:53

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceClinico',
            fields=[
                ('estado_academico', models.CharField(choices=[('BORRADOR', 'Borrador (Editando)'), ('REVISION', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado por Docente'), ('RECHAZADO', 'Rechazado / Con Observaciones')], default='BORRADOR', max_length=20)),
                ('comentarios_docente', models.TextField(blank=True, help_text='Observaciones si rechaza el trabajo', null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_sesion', models.DateField(default=datetime.date.today)),
                ('descripcion_procedimiento', models.TextField(help_text='¿Qué se le hizo al paciente hoy?')),
                ('proxima_cita', models.DateField(blank=True, help_text='Fecha de la siguiente sesión si es necesaria', null=True)),
                ('docente_supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_supervisados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avance de Sesión',
                'verbose_name_plural': 'Avances de Sesiones',
                'ordering': ['-fecha_sesion'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evidencia', models.CharField(choices=[('RADIOGRAFIA', 'Radiografía'), ('FOTO_INICIAL', 'Fotografía Clínica Inicial'), ('FOTO_PROCESO', 'Fotografía Clínica en Proceso'), ('FOTO_FINAL', 'Fotografía Clínica Final'), ('DOCUMENTO', 'Documento / Consentimiento')], max_length=20)),
                ('archivo', models.FileField(upload_to='evidencias_clinicas/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='gestion_clinica.avanceclinico')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo_transferencia', models.TextField(help_text='¿Por qué se deriva al paciente?')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación Docente'), ('APROBADA', 'Transferencia Aprobada'), ('RECHAZADA', 'Transferencia Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Cuando el docente aprobó/rechazó', null=True)),
                ('docente_aprobador', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_evaluadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL)),
                ('estudiante_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_emitidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_transferencias', to='gestion_clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(help_text='Ej: Profilaxis, Exodoncia de 3er Molar', max_length=200)),
                ('diente_pieza', models.CharField(blank=True, help_text='Ej: 14, 46, Toda la boca', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado con Éxito'), ('DERIVADO', 'Derivado a otro estudiante'), ('ABANDONADO', 'Abandonado por el paciente')], default='EN_PROGRESO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tratamientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='gestion_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.AddField(
            model_name='avanceclinico',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='gestion_clinica.tratamiento'),
        ),
    ]
