# Generated by Django 6.0.3 on 2026-04-06 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0002_avanceclinico_evidencia_transferencia_tratamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodontograma',
            fields=[
                ('estado_academico', models.CharField(choices=[('BORRADOR', 'Borrador (Editando)'), ('REVISION', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado por Docente'), ('RECHAZADO', 'Rechazado / Con Observaciones')], default='BORRADOR', max_length=20)),
                ('comentarios_docente', models.TextField(blank=True, help_text='Observaciones si rechaza el trabajo', null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datos_vestibular_superior', models.JSONField(blank=True, default=dict, help_text='Datos de la arcada superior vestibular')),
                ('datos_palatino_superior', models.JSONField(blank=True, default=dict, help_text='Datos de la arcada superior palatino')),
                ('datos_vestibular_inferior', models.JSONField(blank=True, default=dict, help_text='Datos de la arcada inferior vestibular')),
                ('datos_lingual_inferior', models.JSONField(blank=True, default=dict, help_text='Datos de la arcada inferior lingual')),
                ('placa_bacteriana_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="% de Placa (O'Leary)")),
                ('sangrado_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% de Sangrado')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Periodontal')),
                ('pronostico', models.TextField(blank=True, null=True, verbose_name='Pronóstico General y por piezas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('docente_supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_supervisados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodontogramas', to='gestion_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Periodontograma',
                'verbose_name_plural': 'Periodontogramas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
