# Generated by Django 6.0.3 on 2026-04-07 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0003_periodontograma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sillón 01', max_length=50)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('revision', 'En Revisión'), ('falla', 'Con Falla')], default='operativo', max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Características especiales del equipo', null=True)),
                ('ultima_revision', models.DateField(default=django.utils.timezone.now)),
                ('dias_frecuencia_mantenimiento', models.IntegerField(default=180, help_text='Cada cuántos días necesita revisión')),
                ('notas_tecnicas', models.TextField(blank=True, help_text='Registro de fallas comunes o piezas cambiadas', null=True)),
                ('posicion_x', models.FloatField(default=0.0)),
                ('posicion_y', models.FloatField(default=0.0)),
                ('posicion_z', models.FloatField(default=0.0)),
            ],
        ),
    ]
