# Generated by Django 6.0.3 on 2026-04-07 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0004_sillon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillon',
            name='ultima_revision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
