# Generated by Django 4.2.10 on 2026-03-31 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0004_dentalchair_dentist_student_paciente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAnimation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='clinical_animations/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('implant', 'Implant'), ('orthodontics', 'Orthodontics'), ('cleaning', 'Cleaning'), ('extraction', 'Extraction')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lateralidad', models.BooleanField(default=False)),
                ('lateralidad_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('apertura', models.BooleanField(default=False)),
                ('apertura_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('chasquidos', models.BooleanField(default=False)),
                ('chasquidos_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('crepitacion', models.BooleanField(default=False)),
                ('crepitacion_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('desviacion_apertura_cierre', models.BooleanField(default=False)),
                ('desviacion_apertura_cierre_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('dificultad_abrir_boca', models.BooleanField(default=False)),
                ('dificultad_abrir_boca_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('fatiga_dolor_muscular', models.BooleanField(default=False)),
                ('fatiga_dolor_muscular_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('disminucion_apertura', models.BooleanField(default=False)),
                ('disminucion_apertura_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('dolor_apertura', models.BooleanField(default=False)),
                ('dolor_apertura_obs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Examen Clínico y Físico',
                'verbose_name_plural': 'Exámenes Clínicos y Físicos',
            },
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='apertura',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='apertura_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='chasquidos',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='chasquidos_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='crepitacion',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='crepitacion_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='desviacion_apertura_cierre',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='desviacion_apertura_cierre_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='dificultad_abrir_boca',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='dificultad_abrir_boca_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='disminucion_apertura',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='disminucion_apertura_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='dolor_apertura',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='dolor_apertura_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='fatiga_dolor_muscular',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='fatiga_dolor_muscular_obs',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='lateralidad',
        ),
        migrations.RemoveField(
            model_name='examenclinicofisico',
            name='lateralidad_obs',
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='medical_images/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('dicom', 'DICOM'), ('xray', 'X-ray'), ('intraoral_photo', 'Intraoral photo'), ('extraoral_photo', 'Extraoral photo')], default='xray', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='gestion_clinica.paciente')),
            ],
        ),
    ]
