# Generated by Django 4.2.10 on 2026-04-23 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0006_alter_antecedentesperiodontales_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='inasistencias',
            field=models.IntegerField(default=0, help_text='Número de citas no asistidas'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_ESPERA', 'En Espera'), ('ATENDIENDO', 'Atendiendo'), ('NO_ASISTIO', 'No Asistió')], default='RESERVADA', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, help_text='Hora de check-in del paciente', null=True)),
                ('duracion_estimada', models.IntegerField(default=30, help_text='Duración estimada en minutos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_estudiante', to=settings.AUTH_USER_MODEL)),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to='gestion_clinica.sillon')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion_clinica.tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
