# Generated by Django 4.2.10 on 2026-04-23 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0007_paciente_inasistencias_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alerta_abandono',
            field=models.BooleanField(default=False, help_text='Indica si el paciente está en alerta por abandono'),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Acta de abandono', help_text='Título del registro clínico', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='gestion_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
    ]
