# Generated by Django 4.2.10 on 2026-04-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0008_paciente_alerta_abandono_historiaclinica'),
    ]

    operations = [
        # El campo ya existe como 'inasistencias', no necesita renombrarse
    ]
