# Generated by Django 4.2.10 on 2026-04-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0009_rename_contador_inasistencias'),
    ]

    operations = [
        # Set all NULL values to 0 for inasistencias
        migrations.RunSQL(
            sql='''UPDATE pacientes SET inasistencias = 0 WHERE inasistencias IS NULL;''',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
