# Generated by Django 4.2.10 on 2026-04-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0010_fix_counter_field'),
    ]

    operations = [
        # El campo inasistencias ya existe desde la migración 0007
        # No se necesitan operaciones adicionales
    ]
