# Generated by Django 4.2.10 on 2026-04-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0011_add_inasistencias_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_espera_alerta', models.IntegerField(default=15, help_text='Minutos de espera antes de generar alerta roja')),
                ('inasistencias_alerta_abandono', models.IntegerField(default=3, help_text='Número de inasistencias para activar alerta de abandono')),
                ('dias_notificacion_previa', models.IntegerField(default=1, help_text='Días antes de la cita para enviar notificación')),
                ('activa', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuración de Alertas',
                'db_table': 'configuracion_alertas',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de cancelación', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Descripción del motivo de cancelación', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='razon_cancelacion',
            field=models.CharField(blank=True, choices=[('PACIENTE', 'Cancelada por Paciente'), ('ESTUDIANTE', 'Cancelada por Estudiante'), ('DOCENTE', 'Cancelada por Docente'), ('MANTENIMIENTO', 'Cancelada por Mantenimiento'), ('OTRA', 'Otra Razón')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_ESPERA', 'En Espera'), ('ATENDIENDO', 'Atendiendo'), ('NO_ASISTIO', 'No Asistió'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoAbandonoPaciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_abandono', models.DateTimeField(auto_now_add=True)),
                ('inasistencias_totales', models.IntegerField(help_text='Número de inasistencias que provocaron el abandono')),
                ('nota_coordinacion', models.TextField(blank=True, help_text='Observaciones de coordinación', null=True)),
                ('reactivado', models.BooleanField(default=False)),
                ('fecha_reactivacion', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_abandonos', to='gestion_clinica.paciente')),
                ('usuario_que_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandonos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_abandono_pacientes',
                'ordering': ['-fecha_abandono'],
            },
        ),
        migrations.CreateModel(
            name='CitaRecurrente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frecuencia', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=20)),
                ('hora', models.TimeField(help_text='Hora del día para la cita')),
                ('dias_semana', models.CharField(blank=True, help_text='Día(s) de la semana (0-6)', max_length=20, null=True)),
                ('duracion_estimada', models.IntegerField(default=30, help_text='Duración estimada en minutos')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la recurrencia')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin (si no está rellena, es indefinida)', null=True)),
                ('max_ocurrencias', models.IntegerField(blank=True, help_text='Número máximo de citas a generar', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_generacion', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_recurrentes_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='citas_recurrentes_estudiante', to=settings.AUTH_USER_MODEL)),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citas_recurrentes', to='gestion_clinica.sillon')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_recurrentes', to='gestion_clinica.tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_recurrentes', to='gestion_clinica.paciente')),
            ],
            options={
                'db_table': 'citas_recurrentes',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('CANCELACION', 'Cancelación'), ('CHECK_IN', 'Check-in'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20)),
                ('campos_modificados', models.JSONField(default=dict, help_text='JSON con los campos que se modificaron')),
                ('valores_anteriores', models.JSONField(default=dict, help_text='JSON con valores anteriores')),
                ('valores_nuevos', models.JSONField(default=dict, help_text='JSON con valores nuevos')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='gestion_clinica.cita')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_citas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='cita_recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='gestion_clinica.citarecurrente'),
        ),
    ]
