# Generated by Django 4.2.10 on 2026-04-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gestion_clinica.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0012_configuracionalertas_cita_cancelada_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=gestion_clinica.models.upload_to_paciente)),
                ('categoria', models.CharField(choices=[('FACIAL', 'Fotografía Facial'), ('INTRAORAL', 'Fotografía Intraoral'), ('PSP', 'Radiografía Placa de Fósforo'), ('CBCT', 'Captura de Tomografía'), ('PROCESO', 'Seguimiento de Proceso/Laboratorio'), ('FINAL', 'Resultado Final (Post-tratamiento)')], max_length=20)),
                ('pieza_dental', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestion_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Imagen Clínica',
                'verbose_name_plural': 'Imágenes Clínicas',
            },
        ),
    ]
