# Generated by Django 4.2.10 on 2026-04-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0013_imagenclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCaso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asignatura', models.CharField(help_text='Ej: Endodoncia I, Periodoncia II', max_length=100)),
                ('procedimiento_principal', models.CharField(choices=[('PROFILAXIS', 'Profilaxis'), ('ENDODONCIA', 'Endodoncia'), ('ORTODONCIA', 'Ortodoncia'), ('PERIODONCIA', 'Periodoncia'), ('EXODONCIA', 'Exodoncia'), ('RESTAURACION', 'Restauración'), ('PROTODONCIA_FIJA', 'Prostodoncia Fija'), ('PROTODONCIA_REMOVIBLE', 'Prostodoncia Removible'), ('CIRUGIA', 'Cirugía'), ('ODONTOPEDIATRIA', 'Odontopediatría')], max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('TRANSFERIDO', 'Transferido'), ('COMPLETADO', 'Completado')], default='ACTIVO', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True)),
                ('procedimientos_aprobados', models.IntegerField(default=0, help_text='Número de procedimientos aprobados por docente')),
                ('fecha_ultima_actualizacion_avance', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='casos_asignados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_caso', to='gestion_clinica.paciente')),
            ],
            options={
                'verbose_name': 'Asignación de Caso',
                'verbose_name_plural': 'Asignaciones de Caso',
                'db_table': 'asignacion_caso',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSupervision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_hito', models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('INICIO', 'Inicio del Procedimiento'), ('CIERRE', 'Cierre del Procedimiento')], help_text='En qué etapa del procedimiento se requiere supervisión', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado por Docente'), ('RECHAZADO', 'Rechazado / Con Observaciones')], default='PENDIENTE', max_length=20)),
                ('descripcion_solicitud', models.TextField(help_text='Descripción del procedimiento/diagnóstico a supervisar')),
                ('observaciones_docente', models.TextField(blank=True, help_text='Observaciones del docente al rechazar', null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Timestamp de la firma electrónica', null=True)),
                ('asignacion_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_supervision', to='gestion_clinica.asignacioncaso')),
                ('docente_supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisiones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Supervisión',
                'verbose_name_plural': 'Solicitudes de Supervisión',
                'db_table': 'solicitud_supervision',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeño',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Insuficiente')], default=3)),
                ('alerta_temprana', models.BooleanField(default=False, help_text='Marca bajo desempeño detectado')),
                ('motivo_detalle', models.TextField(blank=True, help_text='Detalle de la razón de alerta temprana', null=True)),
                ('manejo_tecnica', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Insuficiente')], default=3)),
                ('bioseguridad', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Insuficiente')], default=3)),
                ('comunicacion_paciente', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Insuficiente')], default=3)),
                ('cumplimiento_tiempo', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Insuficiente')], default=3)),
                ('documentacion', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Insuficiente')], default=3)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitud_supervision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='gestion_clinica.solicitudsupervision')),
            ],
            options={
                'verbose_name': 'Evaluación de Desempeño',
                'verbose_name_plural': 'Evaluaciones de Desempeño',
                'db_table': 'evaluacion_desempeño',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asignatura', models.CharField(help_text='Ej: Endodoncia I, Periodoncia II', max_length=100)),
                ('procedimiento', models.CharField(choices=[('PROFILAXIS', 'Profilaxis'), ('ENDODONCIA', 'Endodoncia'), ('ORTODONCIA', 'Ortodoncia'), ('PERIODONCIA', 'Periodoncia'), ('EXODONCIA', 'Exodoncia'), ('RESTAURACION', 'Restauración'), ('PROTODONCIA_FIJA', 'Prostodoncia Fija'), ('PROTODONCIA_REMOVIBLE', 'Prostodoncia Removible'), ('CIRUGIA', 'Cirugía'), ('ODONTOPEDIATRIA', 'Odontopediatría')], max_length=30)),
                ('cupo_minimo', models.IntegerField(default=1, help_text='Número mínimo de procedimientos requeridos')),
                ('cupo_maximo', models.IntegerField(default=10, help_text='Número máximo recomendado')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Cupo',
                'verbose_name_plural': 'Configuraciones de Cupo',
                'db_table': 'configuracion_cupo',
                'unique_together': {('asignatura', 'procedimiento')},
            },
        ),
    ]
