# Generated by Django 4.2.10 on 2026-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0015_alter_antecedentesperiodontales_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_ESPERA', 'En Espera'), ('ATENDIENDO', 'Atendiendo'), ('FINALIZADO', 'Finalizado'), ('NO_ASISTIO', 'No Asistió'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20),
        ),
    ]
