# Generated by Django 6.0.3 on 2026-05-04 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0015_alter_antecedentesperiodontales_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='gestion_clinica.sillon'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='gestion_clinica.tratamiento'),
        ),
        migrations.AlterField(
            model_name='citarecurrente',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_recurrentes_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citarecurrente',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_recurrentes', to='gestion_clinica.sillon'),
        ),
        migrations.AlterField(
            model_name='citarecurrente',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_recurrentes', to='gestion_clinica.tratamiento'),
        ),
    ]
