# Generated by Django 4.2.10 on 2026-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0016_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_ESPERA', 'En Espera'), ('ATENDIENDO', 'Atendiendo'), ('FINALIZADO', 'Finalizado'), ('REPROGRAMADA', 'Reprogramada'), ('NO_ASISTIO', 'No Asistió'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20),
        ),
    ]
