# Generated by Django 6.0.3 on 2026-05-05 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0016_alter_cita_docente_alter_cita_gabinete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='huella_id',
            field=models.IntegerField(blank=True, help_text='ID del sensor biométrico (huella dactilar)', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('PAUSA', 'Pausa')], default='INGRESO', max_length=20, verbose_name='Tipo de Registro')),
                ('huella_id', models.IntegerField(blank=True, help_text='ID de huella registrada en el dispositivo biométrico', null=True)),
                ('verificado', models.BooleanField(default=True, help_text='¿Huella verificada correctamente por el sistema?')),
                ('usuario', models.ForeignKey(help_text='Usuario que registra la asistencia', on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='gestion_cli_usuario_1030b3_idx'), models.Index(fields=['huella_id'], name='gestion_cli_huella__eee7aa_idx')],
            },
        ),
    ]
