# Generated by Django 5.1.5 on 2026-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0017_customuser_huella_id_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedenteginecologico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el antecedente está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='antecedentenopatologicopersonal',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el antecedente está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicofamiliar',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el antecedente está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='antecedentepatologicopersonal',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el antecedente está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='antecedentesperiodontales',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el antecedente está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='asignacioncaso',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la asignación está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='asignacionpaciente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la asignación está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='auditoriacita',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro de auditoria está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='avanceclinico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el avance está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='cita',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la cita está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='evaluaciondesempeño',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la evaluación está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la evidencia está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='examenclinicofisico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el examen está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='examenperiodontal',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el examen está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='habitos',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro de hábitos está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la historia está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='historiaodontopediatrica',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la historia está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='historicoabandonopaciente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro de abandono está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='imagenclinica',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la imagen está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='periodontograma',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el periodontograma está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='prostodonciafija',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='prostodonciaremovible',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='protocoloquirurgico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el protocolo está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='sillon',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el sillón está activo o en papelera'),
        ),
        migrations.AddField(
            model_name='solicitudsupervision',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la solicitud está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la transferencia está activa o en papelera'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el tratamiento está activo o en papelera'),
        ),
    ]
