# Generated by Django 5.1.5 on 2026-05-19 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0017_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacionCargaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('USADO', 'Usado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_imagen', to='gestion_clinica.paciente')),
            ],
            options={
                'db_table': 'autorizacion_carga_image',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAuditoriaImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_docente', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_estudiante', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_paciente', to='gestion_clinica.paciente')),
            ],
            options={
                'db_table': 'historial_auditoria_imagen',
                'ordering': ['-timestamp'],
            },
        ),
    ]
