# Generated by Django 5.1.5 on 2026-06-02 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0018_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Ej: OEN-611', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Operatoria y Endodoncia I', max_length=200)),
                ('semestre', models.IntegerField(default=5)),
                ('vistas_habilitadas', models.JSONField(default=list, help_text='Lista de vistas/módulos que esta materia habilita')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'materias',
                'ordering': ['semestre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True, help_text='True si el usuario aún está en la clínica')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_clinica.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_asistencia',
                'ordering': ['-hora_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudGuardado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_guardado', models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('ODONTOGRAMA', 'Odontograma'), ('PERIODONTOGRAMA', 'Periodontograma'), ('TRATAMIENTO', 'Plan de Tratamiento'), ('AVANCE', 'Avance Clínico'), ('RADIOGRAFIA', 'Radiografía'), ('ANTECEDENTES', 'Antecedentes'), ('EVALUACION', 'Evaluación General'), ('EXPEDIENTE', 'Expediente Completo')], max_length=30)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del trabajo que quiere guardar')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20)),
                ('justificacion_rechazo', models.TextField(blank=True, help_text='Justificación del docente si rechaza', null=True)),
                ('tiempo_ventana_minutos', models.IntegerField(default=30, help_text='Tiempo en minutos que tiene el estudiante para guardar después de la aprobación')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Momento en que expira el permiso de guardar', null=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_guardado_recibidas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_guardado', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_guardado', to='gestion_clinica.materia')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_guardado', to='gestion_clinica.paciente')),
            ],
            options={
                'db_table': 'solicitud_guardado',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MateriaDocente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='materias_docente', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='gestion_clinica.materia')),
            ],
            options={
                'db_table': 'materia_docente',
                'unique_together': {('materia', 'docente')},
            },
        ),
        migrations.CreateModel(
            name='MateriaEstudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROBADA', 'Aprobada'), ('REPROBADA', 'Reprobada')], default='CURSANDO', max_length=20)),
                ('inscrito_en', models.DateTimeField(auto_now_add=True)),
                ('docente_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_supervisados_materia', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='materias_estudiante', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_inscritos', to='gestion_clinica.materia')),
            ],
            options={
                'db_table': 'materia_estudiante',
                'unique_together': {('materia', 'estudiante')},
            },
        ),
    ]
