# Generated by Django 5.1.5 on 2026-05-19 14:05

import gestion_clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0019_autorizacion_campos_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenclinica',
            name='estado_procesamiento',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Procesado', 'Procesado'), ('Error', 'Error')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='imagenclinica',
            name='hallazgos_ia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagenclinica',
            name='hallazgos_manuales',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagenclinica',
            name='imagen_anotada',
            field=models.ImageField(blank=True, null=True, upload_to=gestion_clinica.models.upload_to_paciente),
        ),
        migrations.AddField(
            model_name='imagenclinica',
            name='tarea_celery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
