# Generated by Django 5.1.5 on 2026-06-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0019_materia_registroasistencia_solicitudguardado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenclinica',
            name='resultados_ia',
            field=models.JSONField(blank=True, default=None, help_text='JSON crudo del pipeline IA (YOLOv8 + OpenCV): detecciones de caries y restauraciones', null=True),
        ),
    ]
