# Generated by Django 5.1.5 on 2026-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0020_imagenclinica_estado_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacioncargaimage',
            name='tiempo_permitido_minutos',
            field=models.IntegerField(blank=True, help_text='Minutos que el docente dio para enviar la radiografía', null=True),
        ),
        migrations.AddField(
            model_name='imagenclinica',
            name='historial_analisis',
            field=models.JSONField(blank=True, help_text='Línea de tiempo con todos los análisis realizados: [{timestamp, tipo, resultados, quien}]', null=True),
        ),
    ]
