# Generated by Django 5.1.5 on 2026-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0020_imagenclinica_resultados_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenclinica',
            name='diagnosticos_usuario',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con los diagnósticos manuales y capturas (snapshots)', null=True),
        ),
    ]
