# Generated by Django 5.1.5 on 2026-06-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0021_imagenclinica_diagnosticos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.ForeignKey(db_column='motivo', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion_clinica.tratamiento'),
        ),
    ]
