# Generated by Django 5.1.5 on 2026-05-19 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0021_autorizacioncargaimage_tiempo_permitido_minutos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_nombre', models.CharField(help_text='Nombre del material', max_length=255, unique=True)),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad actual en stock')),
                ('stock_minimo', models.IntegerField(default=10, help_text='Stock mínimo para alertar')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
                'db_table': 'inventario',
            },
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='pieza_dental',
            field=models.IntegerField(blank=True, help_text='Número de pieza dental (1-32)', null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del tratamiento', max_digits=10),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='procedimiento',
            field=models.CharField(blank=True, help_text='Descripción detallada del procedimiento', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente_Aprobacion', 'Pendiente Aprobación Docente'), ('Aprobado_Por_Pagar', 'Aprobado por Pagar'), ('Pagado_Autorizado', 'Pagado y Autorizado'), ('En_Ejecucion', 'En Ejecución'), ('Finalizado_Pendiente_Nota', 'Finalizado Pendiente Nota'), ('Evaluado', 'Evaluado'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado con Éxito'), ('DERIVADO', 'Derivado a otro estudiante'), ('ABANDONADO', 'Abandonado por el paciente')], default='Pendiente_Aprobacion', max_length=30),
        ),
        migrations.CreateModel(
            name='ControlAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_control', models.CharField(choices=[('Inicial_Plan', 'Control Inicial del Plan'), ('Final_Ejecucion', 'Control Final de Ejecución')], max_length=30)),
                ('aprobado', models.BooleanField(default=False)),
                ('nota_rubrica', models.IntegerField(blank=True, help_text='Nota del 0 al 100', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del docente', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='controles_academicos_realizados', to=settings.AUTH_USER_MODEL)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_academicos', to='gestion_clinica.tratamiento')),
            ],
            options={
                'verbose_name': 'Control Académico',
                'verbose_name_plural': 'Controles Académicos',
                'db_table': 'controles_academicos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DespachoAlmacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insumo_nombre', models.CharField(help_text='Nombre del insumo', max_length=255)),
                ('cantidad_despachada', models.IntegerField(help_text='Cantidad de unidades despachadas')),
                ('estado_entrega', models.CharField(choices=[('Entregado', 'Entregado'), ('Devuelto', 'Devuelto')], default='Entregado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos_almacen', to='gestion_clinica.tratamiento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='despachos', to='gestion_clinica.inventario')),
            ],
            options={
                'verbose_name': 'Despacho Almacén',
                'verbose_name_plural': 'Despachos Almacén',
                'db_table': 'despachos_almacen',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_factura', models.CharField(help_text='Número secuencial de factura', max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, help_text='Monto cancelado', max_digits=10)),
                ('estado_pago', models.CharField(choices=[('Emitido', 'Emitido'), ('Anulado', 'Anulado')], default='Emitido', max_length=20)),
                ('cumplimiento_tributario_id', models.CharField(blank=True, help_text='ID de cumplimiento fiscal', max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='gestion_clinica.tratamiento')),
            ],
            options={
                'verbose_name': 'Pago Factura',
                'verbose_name_plural': 'Pagos y Facturas',
                'db_table': 'pagos_facturas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
