# Generated by Django 5.1.5 on 2026-05-19 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0022_inventario_alter_tratamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='docente_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_docente_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
