# Generated by Django 5.1.5 on 2026-05-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0023_paciente_docente_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
